services:
  - type: web
    name: pdf-ocr-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
